"""link uniops orders to easybooks invoices

Creates the only new table this milestone needs. It is additive: no existing row
is read, changed, or deleted, and no raw EasyBooks payload is touched.

The link lives in UniOps alone. It records what we believe about a relationship
EasyBooks does not model, and creating or removing one changes nothing in
EasyBooks.

Cardinality is left open on purpose - the unique key is the pair, not either
side - because UniGreen has no order data yet to say whether an order splits
across invoices or an invoice covers several orders. A one-to-one key would be a
guess, and an expensive one to reverse once links exist.

Everything else this milestone exposes - accounting status, payment status,
receivables - is derived at query time from this table and the normalized
accounting layer. Nothing derived is stored, so an EasyBooks correction cannot
leave a stale figure behind.

Revision ID: 7dfd34c9902d
Revises: b720deb6b96e
Create Date: 2026-09-09 16:10:01.501940
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7dfd34c9902d'
down_revision: Union[str, Sequence[str], None] = 'b720deb6b96e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_accounting_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('sales_document_id', sa.String(length=36), nullable=False),
    sa.Column('link_method', sa.Enum('MANUAL', 'CUSTOMER_DATE_AMOUNT', name='linkmethod', native_enum=False, length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sales_document_id'], ['sales_documents.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'sales_document_id', name='uq_order_accounting_link')
    )
    with op.batch_alter_table('order_accounting_links', schema=None) as batch_op:
        batch_op.create_index('ix_order_links_order', ['order_id'], unique=False)
        batch_op.create_index('ix_order_links_sales_document', ['sales_document_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_accounting_links', schema=None) as batch_op:
        batch_op.drop_index('ix_order_links_sales_document')
        batch_op.drop_index('ix_order_links_order')

    op.drop_table('order_accounting_links')
    # ### end Alembic commands ###

