"""initial v0.1 schema

Revision ID: 9e47c86f437b
Revises: 
Create Date: 2026-09-08 22:28:10.598453
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9e47c86f437b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tax_code', sa.String(length=50), nullable=True),
    sa.Column('easybooks_accounting_object_code', sa.String(length=100), nullable=True),
    sa.Column('easybooks_source_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('easybooks_accounting_object_code', name='uq_customer_eb_code'),
    sa.UniqueConstraint('easybooks_source_id', name='uq_customer_eb_source_id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index('ix_customers_name', ['name'], unique=False)

    op.create_table('easybooks_sync_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=True),
    sa.Column('to_date', sa.Date(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCEEDED', 'PARTIAL', 'FAILED', name='syncstatus', native_enum=False, length=20), nullable=False),
    sa.Column('documents_seen', sa.Integer(), nullable=False),
    sa.Column('documents_created', sa.Integer(), nullable=False),
    sa.Column('documents_updated', sa.Integer(), nullable=False),
    sa.Column('documents_unchanged', sa.Integer(), nullable=False),
    sa.Column('documents_failed', sa.Integer(), nullable=False),
    sa.Column('reconciliation_warnings', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('easybooks_sync_runs', schema=None) as batch_op:
        batch_op.create_index('ix_sync_runs_started', ['started_at'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('easybooks_material_goods_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_product_code'),
    sa.UniqueConstraint('easybooks_material_goods_id', name='uq_product_eb_material_id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('ix_products_name', ['name'], unique=False)

    op.create_table('purchase_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=True),
    sa.Column('source_document_number', sa.String(length=100), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('vendor_code', sa.String(length=100), nullable=True),
    sa.Column('vendor_name', sa.String(length=255), nullable=True),
    sa.Column('tax_code', sa.String(length=50), nullable=True),
    sa.Column('currency_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('total_purchase_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('normalized_hash', sa.String(length=64), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system', 'source_id', name='uq_purchase_source')
    )
    with op.batch_alter_table('purchase_documents', schema=None) as batch_op:
        batch_op.create_index('ix_purchase_document_date', ['document_date'], unique=False)
        batch_op.create_index('ix_purchase_vendor_code', ['vendor_code'], unique=False)

    op.create_table('sales_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=True),
    sa.Column('source_document_number', sa.String(length=100), nullable=True),
    sa.Column('company_id', sa.String(length=100), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('invoice_series', sa.String(length=100), nullable=True),
    sa.Column('accounting_object_code', sa.String(length=100), nullable=True),
    sa.Column('accounting_object_name', sa.String(length=255), nullable=True),
    sa.Column('currency_id', sa.String(length=20), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('recorded', sa.Boolean(), nullable=True),
    sa.Column('normalized_hash', sa.String(length=64), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system', 'source_id', name='uq_sales_source')
    )
    with op.batch_alter_table('sales_documents', schema=None) as batch_op:
        batch_op.create_index('ix_sales_customer_code', ['accounting_object_code'], unique=False)
        batch_op.create_index('ix_sales_document_date', ['document_date'], unique=False)

    op.create_table('easybooks_raw_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('sync_run_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['sync_run_id'], ['easybooks_sync_runs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system', 'entity_type', 'source_id', 'payload_hash', name='uq_raw_source_payload')
    )
    with op.batch_alter_table('easybooks_raw_records', schema=None) as batch_op:
        batch_op.create_index('ix_raw_lookup', ['source_system', 'entity_type', 'source_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_number', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'SCHEDULED', 'IN_PRODUCTION', 'READY', 'DELIVERY_PENDING', 'DELIVERED', 'INVOICED', 'CLOSED', 'CANCELLED', name='orderstatus', native_enum=False, length=32), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('required_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number', name='uq_order_number')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('ix_orders_customer', ['customer_id'], unique=False)
        batch_op.create_index('ix_orders_status_required', ['status', 'required_date'], unique=False)

    op.create_table('purchase_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('purchase_document_id', sa.String(length=36), nullable=False),
    sa.Column('source_line_key', sa.String(length=64), nullable=False),
    sa.Column('material_goods_code', sa.String(length=100), nullable=True),
    sa.Column('material_goods_name', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('purchase_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('warehouse_code', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['purchase_document_id'], ['purchase_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_document_id', 'source_line_key', name='uq_purchase_line_source')
    )
    with op.batch_alter_table('purchase_lines', schema=None) as batch_op:
        batch_op.create_index('ix_purchase_lines_document', ['purchase_document_id'], unique=False)
        batch_op.create_index('ix_purchase_lines_product_code', ['material_goods_code'], unique=False)

    op.create_table('sales_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sales_document_id', sa.String(length=36), nullable=False),
    sa.Column('source_line_key', sa.String(length=64), nullable=False),
    sa.Column('source_line_id', sa.String(length=100), nullable=True),
    sa.Column('material_goods_id', sa.String(length=100), nullable=True),
    sa.Column('material_goods_code', sa.String(length=100), nullable=True),
    sa.Column('material_goods_name', sa.String(length=255), nullable=True),
    sa.Column('repository_code', sa.String(length=100), nullable=True),
    sa.Column('accounting_object_code', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sales_document_id'], ['sales_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sales_document_id', 'source_line_key', name='uq_sales_line_source')
    )
    with op.batch_alter_table('sales_lines', schema=None) as batch_op:
        batch_op.create_index('ix_sales_lines_document', ['sales_document_id'], unique=False)
        batch_op.create_index('ix_sales_lines_product_code', ['material_goods_code'], unique=False)

    op.create_table('order_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('agreed_unit_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'position', name='uq_order_line_position')
    )
    with op.batch_alter_table('order_lines', schema=None) as batch_op:
        batch_op.create_index('ix_order_lines_order', ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_lines', schema=None) as batch_op:
        batch_op.drop_index('ix_order_lines_order')

    op.drop_table('order_lines')
    with op.batch_alter_table('sales_lines', schema=None) as batch_op:
        batch_op.drop_index('ix_sales_lines_product_code')
        batch_op.drop_index('ix_sales_lines_document')

    op.drop_table('sales_lines')
    with op.batch_alter_table('purchase_lines', schema=None) as batch_op:
        batch_op.drop_index('ix_purchase_lines_product_code')
        batch_op.drop_index('ix_purchase_lines_document')

    op.drop_table('purchase_lines')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_status_required')
        batch_op.drop_index('ix_orders_customer')

    op.drop_table('orders')
    with op.batch_alter_table('easybooks_raw_records', schema=None) as batch_op:
        batch_op.drop_index('ix_raw_lookup')

    op.drop_table('easybooks_raw_records')
    with op.batch_alter_table('sales_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_sales_document_date')
        batch_op.drop_index('ix_sales_customer_code')

    op.drop_table('sales_documents')
    with op.batch_alter_table('purchase_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_purchase_vendor_code')
        batch_op.drop_index('ix_purchase_document_date')

    op.drop_table('purchase_documents')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('ix_products_name')

    op.drop_table('products')
    with op.batch_alter_table('easybooks_sync_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_sync_runs_started')

    op.drop_table('easybooks_sync_runs')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index('ix_customers_name')

    op.drop_table('customers')
    # ### end Alembic commands ###

